// OBJECTIVE
// How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

#include <iostream>
#include <string>
#include <set>
#include "../include/MathUtils.hpp"
using namespace std;
string num1;


    
int main() 
{
    set<string> Powers; // Set does not contain duplicate elements, set  automatically ignores them
    for (int a = 2; a <= 100; a++) 
    {
        for (int b = 2; b <= 100; b++) 
        {
            num1 = "1";
            for (int i = 0; i < b; i++)
                num1 = Mathutilus::PowofString(num1, a);
            Powers.insert(num1);
        }
    }
    cout << Powers.size() << endl;
}
