// OBJECTIVE
// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
// Triangle: T_n = n(n+1)/2, Pentagonal: P_n = n(3n−1)/2, Hexagonal: H_n = n(2n−1).
// Find the next triangle number that is also pentagonal and hexagonal (after 40755).

#include <iostream>
#include <math.h>
#include "../include/MathUtils.hpp"
using namespace std;
long long int counter,sum;

int main()
{
    counter =40755;
    while (true)
    {
        sum=(counter*counter+counter)/2; //triangle rule x=(n^2+n)/2
        if (Mathutilus::isHexagon(sum)&&Mathutilus::isPentagon(sum))    {cout <<sum;    break;}
        i++;
    }
}