// OBJECTIVE
// The sequence of triangle numbers is generated by adding the natural numbers. 
// The 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
// 28 is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred divisors?

#include <iostream>
#include <math.h>
#include "../include/MathUtils.hpp"

using namespace std;
int counter=50,result=0,temp,dividerCounter,nOD; //nOD is number of dividers
int prime[750],primeCounter=0;

int main()
{
    for (size_t i = 2; i <= 3000; i++) //finds prime numbers
    {
        if (Mathutils::IsPrime(i)) 
        {
            prime[primeCounter]=i;
            primeCounter++;
        }
    }
    for (size_t i = 1; i < 50; i++) result+=i; //for lesser execution time we start at 50 
    while (true)
    {
        result+=counter; temp=result; nOD=1;
        for (size_t i = 0; i < primeCounter; i++)
        {
            dividerCounter=0;
            while(temp%prime[i]==0) {temp/=prime[i]; dividerCounter++;} // Finds prime factors powers to use factor formula based on prime powers
            nOD*=dividerCounter+1;
        }
        if (nOD>500) break;
        counter++;
    }
cout << result;
}