// OBJECTIVE
// The digit factorial chain for a number is generated by summing the factorials of its digits iteratively until a cycle is reached.
// A chain terminates its non-repeating sequence as soon as a previously generated number reappears (e.g., 69 -> 363600 -> 1454 -> 169 -> 363601 -> 1454...).
// Determine the number of starting values strictly below 1,000,000 (10^6) that produce a chain containing exactly sixty non-repeating terms.
// What is the count of such starting numbers?

#include <iostream>
#include <math.h>
#include <set>
#include "../include/MathUtils.hpp"
using namespace std;
set<int> nonRepeat;
bool flag;
int result,counter;
long int temp1,temp2,temp3;


int main()
{
    for (int i = 1; i < 1000000; i++)// Iteratively compute the digit factorial sum and update temp1 
                                    // until a cycle is detected or the chain length exceeds 60.
    {
        nonRepeat.clear(); temp1=i; counter=1;
        nonRepeat.insert(i); flag=true;
        while(flag)
        {
            temp2=0;
            while(temp1>=1)// Compute the sum of factorials of each digit for the current number
            {
                temp2+=Mathutilus::Factoriel(temp1%10);
                temp1/=10;
            }
            temp1=temp2;
            nonRepeat.insert(temp2);
            counter++;
            if(counter!=nonRepeat.size()||nonRepeat.size()>60) {flag=false;}//verifies if number starts repeat chain
        }
        if (nonRepeat.size()==60)   {result++; cout << i << endl;}
    }
    
    cout << result;
}