// OBJECTIVE
// Pentagonal numbers are generated by the formula, P_n = n(3n−1)/2.
// Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference 
// are pentagonal and D = |P_k − P_j| is minimised; what is the value of D?

#include <iostream>
#include <math.h>
#include "../include/MathUtils.hpp"
using namespace std;
long long int pentagon[10000];
long long int temp1,temp2;
bool flag=true;

int main() 
{
    for (int i = 1; i < 10001; i++)     pentagon[i-1]=(3*i*i-i)/2; // stores first 10000 pentagon number in an array
    for (int i = 0; i < 10000 && flag; i++)
    {
        for (int k = i+1; k < 10000; k++)
        {
            temp1=pentagon[i]+pentagon[k];temp2=pentagon[k]-pentagon[i];
            if (Mathutilus::isPentagon(temp1)&&Mathutilus::isPentagon(temp2))
            {
                cout<<pentagon[k]-pentagon[i];
                flag=false; // stop nested loop when find first number
            }            
        }
    }
}
